apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: utsavdemo
  name: utsavdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: utsavdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: utsavdemo
    spec:
      containers:
      - image: us1313/repo6:latest
        name: utsavdemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9090
  selector:
    app: utsavdemo

